# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countrys',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('air_date', models.DateField(blank=True, null=True)),
                ('number', models.IntegerField()),
                ('tmdb_id', models.IntegerField()),
                ('overview', models.TextField(blank=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Episode',
                'verbose_name_plural': 'Episodes',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('also_known_as', models.TextField(blank=True)),
                ('biography', models.TextField(blank=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('deathday', models.DateField(blank=True, null=True)),
                ('tmdb_id', models.IntegerField()),
                ('place_of_birth', models.CharField(blank=True, max_length=254)),
                ('profile_small', models.ImageField(blank=True, max_length=254, null=True, upload_to='tv/profile/person/small')),
                ('profile_medium', models.ImageField(blank=True, max_length=254, null=True, upload_to='tv/profile/person/medium')),
                ('profile_large', models.ImageField(blank=True, max_length=254, null=True, upload_to='tv/profile/person/large')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('air_date', models.DateField()),
                ('tmdb_id', models.IntegerField()),
                ('poster_small', models.ImageField(blank=True, max_length=254, null=True, upload_to='tv/poster/season/small')),
                ('poster_medium', models.ImageField(blank=True, max_length=254, null=True, upload_to='tv/poster/season/medium')),
                ('poster_large', models.ImageField(blank=True, max_length=254, null=True, upload_to='tv/poster/season/large')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('poster_small', models.ImageField(blank=True, max_length=254, null=True, upload_to='tv/poster/series/small')),
                ('poster_medium', models.ImageField(blank=True, max_length=254, null=True, upload_to='tv/poster/series/medium')),
                ('poster_large', models.ImageField(blank=True, max_length=254, null=True, upload_to='tv/poster/series/large')),
                ('in_production', models.BooleanField()),
                ('first_air_date', models.DateField(blank=True, null=True)),
                ('episode_run_time', models.DurationField(blank=True, null=True)),
                ('last_air_date', models.DateField(blank=True, null=True)),
                ('number_of_episodes', models.IntegerField()),
                ('number_of_seasons', models.IntegerField()),
                ('original_language', models.CharField(blank=True, max_length=4)),
                ('overview', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(to='tv.Genre')),
                ('origin_country', models.ManyToManyField(to='tv.Country')),
            ],
            options={
                'verbose_name': 'Series',
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.AddField(
            model_name='episode',
            name='season_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv.Season'),
        ),
    ]
