# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0002_auto_20151219_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='series_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tv.Series'),
            preserve_default=False,
        ),
    ]
