# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0004_auto_20151223_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='episode_run_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
