# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0006_auto_20151224_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='poster_medium',
        ),
        migrations.RemoveField(
            model_name='series',
            name='poster_medium',
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', related_query_name='credit', to='tv.Department'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', related_query_name='credit', to='tv.Job'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', related_query_name='credit', to='tv.Person'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', related_query_name='credit', to='tv.Series'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', related_query_name='episode', to='tv.Season'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', related_query_name='episode', to='tv.Series'),
        ),
        migrations.AlterField(
            model_name='job',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', related_query_name='job', to='tv.Department'),
        ),
        migrations.AlterField(
            model_name='season',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', related_query_name='season', to='tv.Series'),
        ),
    ]
