# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0007_auto_20151228_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='name',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='season',
            name='air_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
