# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0008_auto_20151230_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['-number'], 'verbose_name': 'Episode', 'verbose_name_plural': 'Episodes'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['number'], 'verbose_name': 'Season', 'verbose_name_plural': 'Seasons'},
        ),
    ]
