# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 15:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tv', '0010_auto_20160116_1617'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv.Series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Watchlist',
                'verbose_name_plural': 'Watchlists',
                'ordering': ['-added'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together=set([('series', 'user')]),
        ),
    ]
