# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlog',
            unique_together=set([('episode', 'user')]),
        ),
    ]
