# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlog', '0002_auto_20160115_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlog',
            options={'ordering': ['-added'], 'verbose_name': 'Watchlog', 'verbose_name_plural': 'Watchlogs'},
        ),
    ]
